language: ruby

matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: rbx-2

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - jruby-18mode
  - jruby-19mode
  - rbx-2

script:
  - (cd test/dummy && RAILS_ENV=test bundle exec rake --trace db:migrate test)
